name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          #Your Ml workflow goes there
          pip install -r requirements.txt
          python train.py
 
          echo "## model metrics" >> report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml comment feature_importance.png --md >> report.md
          cml comment residuals.png --md >> report.md

          cml comment create report.md

          
          
          
       
